### ISSUE TITLE
AFI templates attempt to load some mods not present on Anrop repo or differently named

### ISSUE THREAD

**Issue by rundabollen** [Anrop/Anrop-PlayWithSix#131]
For example `Template - AFI - armafinland.fi WW2` attempts to load `@zlusken_whistle_and_bugle` rather than `@zsn_visselpipa`. Possible fix might be to for missing mods look for identical keys in other mods or to have manual switch case for some mods?

**Comment by rundabollen** [comment]
dunno how to set label but this is minor ofc

**Comment by Dahlgren** [comment]
Working as intended

**Comment by Dahlgren** [comment]
@rundabollen if you want template to match repo then rename mods on the repo to the AFI name
